# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test
on: [push, pull_request]
jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "RelWithDebInfo"]
        generator: ["Ninja", "Unix Makefiles"]
        compiler: ["clang", "gcc"]
        container_version: [20220301]

    container: ghcr.io/${{ github.repository }}:${{ matrix.container_version }}

    steps:
      - name: Checkout
        run: |
          git init source && \
          cd source && \
          git remote add origin ${{ github.repositoryUrl }} && \
          git fetch --depth 1 origin ${{ github.sha }} && \
          git checkout FETCH_HEAD

      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=devops/toolchain/${{ matrix.compiler }} \
            -G "${{ matrix.generator }}" \
            -S source \
            -B cmake-build-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Build
        run: cmake --build .
        working-directory: cmake-build-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Test
        run: ctest --output-on-failure
        working-directory: cmake-build-${{ matrix.build_type }}-${{ matrix.compiler }}

      - name: Formatting
        run: cmake --build . --target format
        working-directory: cmake-build-${{ matrix.build_type }}-${{ matrix.compiler }}
